### ISSUE TITLE
Crash on large area (Europe 10m inverval  - view1)

### ISSUE THREAD

**Issue by extremecarver** [agrenott/pyhgtmap#10]
hgt file /home/contourlines/hgt/VIEW1/N38E012.hgt: 3601 x 3601 points, bbox: (12.00000, 38.00000, 13.00000, 39.00000)
Traceback (most recent call last):
  File "/home/contourlines/my_venv/bin/pyhgtmap", line 8, in <module>
    sys.exit(main())
  File "/home/contourlines/my_venv/lib/python3.10/site-packages/pyhgtmap/main.py", line 589, in main
    HgtFilesProcessor(opts.nJobs, opts.startId, opts.startWayId).process_files(
  File "/home/contourlines/my_venv/lib/python3.10/site-packages/pyhgtmap/hgt/processor.py", line 177, in process_files
    self.process_file(file_name, check_poly, options)
  File "/home/contourlines/my_venv/lib/python3.10/site-packages/pyhgtmap/hgt/processor.py", line 173, in process_file
    self.process_tile(file_name, tile, options)
  File "/home/contourlines/my_venv/lib/python3.10/site-packages/pyhgtmap/hgt/processor.py", line 143, in process_tile
    p.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 65, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files

Trying pyhgtmap on Europe with 10m inverval (view1) it crashed out like this. I will try again with jobs=2 instead of jobs=12 but I'm pretty sure it did not run out of memory. Asia would be a whole different animal - took me many tries on old phyghtmap to get it working (though I think the main problem was splitting the outpup file with mkgmap splitter)

**Comment by extremecarver** [comment]
could you try with -o5m as output? 

But after merging to pbf it's fine. I wonder why the o5m files need such a huge space requirement (not sure I can compile Asia continent without running out of disk space if there also happens such big o5m files. I only have abour 2TB available free (with Asia continent size becomes a bit relative) (my processor is AMD Ryzen 5 3600 so no way as fast as your i5-13600 - max 50% but the server has 64GB RAM/6TB HDD besides 512GB NVME)

**Comment by extremecarver** [comment]
e.g.
lon6.00_7.00lat45.00_46.00_view1.o5m
lon6.00_7.00lat44.00_45.00_view1.o5m
lon7.00_8.00lat45.00_46.00_view1.o5m

are all around 200MB in size (the whole Alps around Valais and South of it is responsible for huge size, but also the Pyrenes create some pretty big files in o5m format. But yeah I guess that's because o5m is very fast but not compressed. Too bad pbf cannot be merged with osmconvert. I guess if you need Asia in one file then single file output is the only way (o5m.gz is not possible either I think for osmconvert - and using osmosis would be super slow and not sure)

Osmium seems to be able to merge pbf files - I will give this a try tomorrow if it works (and should even work with wildcards unlike osmconvert which expects a full file list)

**Comment by agrenott** [comment]
Looks like you set insane value to --max-nodes-per-tile, as you shouldn't have a single output for a whole tile. In my case it's split into much smaller tiles, for eg. `lon6.00_7.00lat45.22_45.25_view1.o5m`.

**Comment by extremecarver** [comment]
well - osmconvert can maximum do 1001 files per call. So that kinda makes it impossible. I will see if osmium chokes or not on 1677 o5m files totalling 44.2GB. It needed 52GB of Memory and 18 minutese to merge them.
(my server needed 2:20 hours to create the files with pyhgtmap - so ovrall 2:38)

I'll also run pyhgtmap with --pbf option for output and then see if osmium can merge them and how much memory it needs. But I think there is a need for a single output file mode because otherwise even systems with 128GB won't be able to compile Asia or South-America contourlines, maybe not even Africa or China. All of which are substantially larger than Europe continent.
