### ISSUE TITLE
How to update from Github Code snaptshot?

### ISSUE THREAD

**Issue by extremecarver** [agrenott/pyhgtmap#12]
When I run
pip install -U pyhgtmap

nothing happens - because I think the main version is still 3.0.0. Could you please add an explanation on how to update to latest sourcode from Github? Where do I need to move this code and what to run then?

**Comment by agrenott** [comment]
`pip install -U git+https://github.com/agrenott/pyhgtmap.git` should do the trick.

**Comment by extremecarver** [comment]
Great thanks. Would be great to add that to the documentation for people not often using pip (and needs apt-get install git)
