### ISSUE TITLE
"Killed"

### ISSUE THREAD

**Issue by extremecarver** [agrenott/pyhgtmap#16]
hgt file /home/contourlines/hgt/SRTM1v3.0/N25E003.hgt: 3601 x 3601 points, bbox: (3.00000, 25.00000, 4.00000, 26.00000)
Killed

not sure why this is happening - command was: 
 nice -n 19 pyhgtmap --earthexplorer-user=extremecarver --earthexplorer-password=Testmap0 --jobs=10 --polygon=/home/contourlines/bounds/africa.poly --step=10 --no-zero-contour --void-range-max=-420 --output-prefix=africa --line-cat=$detail --start-node-id=10000000 --start-way-id=10000000 --source=view1,srtm1,view3,srtm3 --max-nodes-per-way=230 --max-nodes-per-tile=0 --pbf --hgtdir=/home/contourlines/hgt  -j16

With around 62GB of available RAM. Did id run out of memory? I will rerun with --jobs=2 but a bit better error message why it was killed would be great. Europe was killed as well. with above command.

**Comment by extremecarver** [comment]
Tried with jobs=2 and it got killed exactly at the same place after writing 1.9GB of data

**Comment by agrenott** [comment]
There was indeed a memory leak, keeping data between tiles.
It should be fixed now. I've been able to generate significant part of Africa (4.7GB output) before aborting. 
Please note ways are accumulated until the end, and file is committed at once by pyosmium, so memory requirement for such an area is still significant.

**Comment by agrenott** [comment]
FYI, I've been able to finish Africa with a single output file. Took ~80 minutes and output is 6.3 GB.

**Comment by extremecarver** [comment]
Phyghtmap was using less memory compared to even after fixing this. With 64GB RAM I cannot compile Africa 10m interval (13.9GB) anymore. Not to mention Asia 10m (66GB).
I'm not sure if there is maybe another bug or the changes improve performance at the expense of memory. It aborted at nearly 11GB.

**Comment by agrenott** [comment]
Are you sure you're using the 3.1 version?
I'm able to generate the africa 10m, despite using a lot of memory:
![image](https://github.com/agrenott/pyhgtmap/assets/12431371/ec0d9dde-41e2-47df-bafc-5bf562800fee)

But then I agree 24GB of memory seems excessive to output a file which is "only" 6.3GB... There's probably some useless accumulation of objects somewhere.

**Comment by extremecarver** [comment]
Actually right now with 10.6GB written out - it uses 61GB RAM already. Something is definitely wrong still or we will need to use the phyghtmap with the first patch to get it running for Asia/China/Russia/South America/Africa on a 64GB RAM machine (haven*t tried to increase virtual memory to say 128GB or similar - which maybe okay for the usecase)

**Comment by agrenott** [comment]
Well, I'm actually using the command you originally shared, so 10m steps. The difference being it's 1" and 3" (but 1" should be favored when available).
```
pyhgtmap --jobs=10 --polygon=africa.poly --step=10 --no-zero-contour --void-range-max=-420 --output-prefix=africa  --start-node-id=10000000 --start-way-id=10000000 --source=view1,srtm1,view3,srtm3 --max-nodes-per-way=230 --max-nodes-per-tile=0 --pbf --hgtdir=/mnt/g/git/garmin_mtb/work/hgt/ --log=DEBUG
```

**Comment by agrenott** [comment]
I've setup an account for SRTM1", and it works fine.
Anyway, the memory usage seems in fact logical, beside being un-optimized: I need to keep the list of ways to be written after all nodes. Each way is a tuple of 3 ints and a bool, but it actually uses A LOT of memory in Python:
```
from pympler import asizeof
a=pyhgtmap.output.WayType(next_node_id, len(contour), is_closed_way, elevation)
asizeof.asized(a, detail=1).format()
'WayType(first_node_id=10000000, nb_nodes=1695, closed_loop=False, elevation=0) size=184 flat=72\n    10000000 size=32 flat=32\n    1695 size=32 flat=32\n    False size=24 flat=24\n    0 size=24 flat=24\n    __class__ size=0 flat=0'
```

184 bytes for each way. As the output for Africa has (tens of?) millions of ways, the actual memory usage is HUGE...
I'll try to see whether more efficient storage (array or numpy.array) improves this significantly.

**Comment by extremecarver** [comment]
But how was it possible with the old phyghtmap to use approx only 1/6 of memory? I think the easiest is just an option for a temp file. Yeah that would mean 360GB or so for Asia, but that is much easier to have on a computer than 360GB of memory... (and increasing swap for that size I'm not sure how good the memory management in Linux could handle that). If one is to compute such a huge file, some hundred GB of tempfile space shouldn't be an issue. Storing all those hgts anyhow takes up huge space too so someone trying this likely has a big HDD for data storage besides a fast system drive anyhow.

**Comment by extremecarver** [comment]
It's not that I actually need this - lately there have been no significant updates to 1" source data outside of Europe and north America when it comes to higher quality - and I still have the old pbf output files - I noticed it with Europe and then just wanted to give Africa a try being a couple of times bigger.

**Comment by agrenott** [comment]
My Africa dataset contains almost 100 million ways. Relying on numpy array instead of list of tuples reduces memory consumption by about 10x factor (2.6GB consumed at the end of the process):
```
time pyhgtmap --jobs=10 --polygon=africa.poly --step=10 --no-zero-contour --void-range-max=-420 --output-prefix=africa  --start-node-id=10000000 --start-way-id=10000000 --source=view1,srtm1,view3,srtm3 --max-nodes-per-way=230 --max-nodes-per-tile=0 --pbf --hgtdir=/mnt/g/git/garmin_mtb/work/hgt/ --log=DEBUG
...
2023-06-02 01:56:04,878 - pyhgtmap.output:79:DEBUG - 27675 - done() - Writing 92957050 pending ways
2023-06-02 02:10:53,604 - pyhgtmap.output:82:DEBUG - 27675 - done() - done!

real    50m31.503s
user    20m44.594s
sys     0m12.000s
```

**Comment by extremecarver** [comment]
Well I now have another problem with the newest version - seems there are problems with order - when trying to split the output with mkgmap splitter - I get the error:
Error: Node ids are not sorted. Use e.g. osmosis to sort the input data.
This is not supported with keep-complete=true or --problem-list
uk.me.parabola.splitter.SplitFailedException: Node ids are not sorted

Old versions never had that problem. Running osmosis on this data to sort it - would again fail due to size constraints.

Speed and Memory use are great however now!

**Comment by agrenott** [comment]
That's a bit strange as I didn't change the nodes management with the latest change.
Could the error message reference the nodes references inside a way?
Or if it's only on big dataset, it might have "always" been here, possibly due to some integer overflow on nodes IDs... Any way to get more details by increasing verbosity of osmosis? (seeing the ID going from big positive to negative value could confirm the hypothesis).

**Comment by extremecarver** [comment]
Those files crash Osmosis running out of memory If I try to use Osmosis to sort it. 
I could only try to run the patched phyghtmap on Europa and see if it goes through - I guess yes. Especially with Africa I don't think any of my input files changed since last succesful run. 

The error message if from mkgmap splitter.

**Comment by extremecarver** [comment]
BTW - I downloaded a fresh copy of S20W180 from SRTM and the above small bug still happens.  (this source gives directly hgt not tif files for download)
https://dwtkns.com/srtm30m/

Also the download tool crashed when it tried to download with correct username/password (or maybe crashed on unzipping):
S20W180: trying view1 ...
S20W180: trying srtm1v3.0 ...
S20W180: downloading file https://earthexplorer.usgs.gov/download/5e83a3efe0103743/SRTM1S20W180V3/EE to /home/contourlines/hgt/SRTM1v3.0/S20W180.tif ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 779, in downloadAndUnzip_Tif
    os.stat(saveFilename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/contourlines/hgt/SRTM1v3.0/S20W180.tif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyhgtmap", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/main.py", line 561, in main
    hgtDataFiles = NASASRTMUtil.getFiles(
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 887, in getFiles
    saveFilename = getFile(area, source)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 876, in getFile
    return downloadAndUnzip(url, area, source)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 762, in downloadAndUnzip
    return downloadAndUnzip_Tif(url, area, source)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 784, in downloadAndUnzip_Tif
    downloadToFile(url, saveFilename, source)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 756, in downloadToFile
    return downloadToFile_SRTMv3(url, filename)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 731, in downloadToFile_SRTMv3
    opener = earthexplorerLogin()
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 726, in earthexplorerLogin
    res2 = opener.open(req2)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by extremecarver** [comment]
I will try tomorrow using this version (I think this one must still be close to identical and I believe it will run under current Ubuntu):
https://github.com/agrenott/pyhgtmap/tree/798b96552cfae00a7db764c5e26d790b20feedb2

or should I even downgrade to this one:
https://github.com/agrenott/pyhgtmap/tree/6062a7b75fcf7e70d63843daad9d624f3280e279
?

At the same time I'm just running the most recent version vs South-America and Asia and see if it splits or not. On both continents I definitely didn't change any input data since the last succesful run.

**Comment by agrenott** [comment]
> BTW - I downloaded a fresh copy of S20W180 from SRTM and the above small bug still happens. (this source gives directly hgt not tif files for download) https://dwtkns.com/srtm30m/
> 
> Also the download tool crashed when it tried to download with correct username/password (or maybe crashed on unzipping): S20W180: trying view1 ... S20W180: trying srtm1v3.0 ... S20W180: downloading file https://earthexplorer.usgs.gov/download/5e83a3efe0103743/SRTM1S20W180V3/EE to /home/contourlines/hgt/SRTM1v3.0/S20W180.tif ... Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 779, in downloadAndUnzip_Tif os.stat(saveFilename) FileNotFoundError: [Errno 2] No such file or directory: '/home/contourlines/hgt/SRTM1v3.0/S20W180.tif'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/bin/pyhgtmap", line 8, in sys.exit(main()) File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/main.py", line 561, in main hgtDataFiles = NASASRTMUtil.getFiles( File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 887, in getFiles saveFilename = getFile(area, source) File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 876, in getFile return downloadAndUnzip(url, area, source) File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 762, in downloadAndUnzip return downloadAndUnzip_Tif(url, area, source) File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 784, in downloadAndUnzip_Tif downloadToFile(url, saveFilename, source) File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 756, in downloadToFile return downloadToFile_SRTMv3(url, filename) File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 731, in downloadToFile_SRTMv3 opener = earthexplorerLogin() File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 726, in earthexplorerLogin res2 = opener.open(req2) File "/usr/lib/python3.10/urllib/request.py", line 525, in open response = meth(req, response) File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response response = self.parent.error( File "/usr/lib/python3.10/urllib/request.py", line 563, in error return self._call_chain(*args) File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain result = func(*args) File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 401: Unauthorized

```
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```
You have a credentials issue. You may delete your `~/.pyhgtmaprc` to ensure it's not trying to use an old one.
