### ISSUE TITLE
Maybe add note about lxml requirement in the README

### ISSUE THREAD

**Issue by janosrusiczki** [agrenott/pyhgtmap#22]
I'm trying to use pyhgtmap in a Docker container starting `FROM debian:bookworm-slim` with the following packages installed through apt:

```
python3
python3-pip
python3-venv
python3-gdal
```

However I was getting the following error:

    bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

So I added:

```
python3-lxml
```
to the list of apt packages to be installed. Now I'm getting the following warning:

```
/opt/venv/lib/python3.11/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(
```
After which it proceeds to download the files.

Is this warning normal or have I made a mistake?

**Comment by agrenott** [comment]
You're right, I will add the explicit lxml dependency as it's set when instantiating BS.
I'll have a look at the warning as well, but I don't think it has real consequences.
