### ISSUE TITLE
Unable to install newest version (3.5.3) directly from git (Python Version issue?)

### ISSUE THREAD

**Issue by keenonkites** [agrenott/pyhgtmap#33]
I've noticed that you added the possibility to directly download hgt from Sonny. Helpful feature...

Unfortunately I've tried it out on Ubuntu 20.04 and did get the following error message:
ERROR: Package 'pyhgtmap-3.5.3.dev3-g192dadb' requires a different Python: 3.8.10 not in '>=3.9'

Did you drop Python 3.8 support or is this just an intermediate issue/problem ?

Thanks for clarifying.
Patrik

**Comment by agrenott** [comment]
Actually python 3.8 was never explicitly supported.
I added it as there was no actual limitation (only typing).
But I don't plan to maintain it once 3.8 becomes EOL in few months.

**Comment by keenonkites** [comment]
Thanks for the feedback and for re-enabling 3.8 for the moment.... I will try organize to install newer version in parallel to the standard python version that comes with the system.
Cheers Patrik
