### ISSUE TITLE
Could we use the files from RGEalti IGN ?

### ISSUE THREAD

**Issue by ravenfeld** [agrenott/pyhgtmap#37]
Hello,

I'm not in the field and I'm having trouble knowing whether what I'm trying to do is feasible or not, or simply useless.

Let me explain.

I made a rendering for Garmin https://ravenfeld.gitlab.io/open-garmin-map/ devices thanks to your program.

Except that I find that the contour lines are not very smooth and that this may be linked to the file I'm using. (Sonny 1° or Nasa 1° for countries outside Europe).

I thought that for the map of France I could use a better file by using the RGEalti files https://www.geoportail.gouv.fr/donnees/rge-alti-sources, but the files are in .asc and not hgt.

I've tried using gdal to convert them but without success so far.

With a bit of digging, I realized that hgt has an accuracy of 30m, so converting from .asc to .hgt would be pointless.
What's the difference between all the formats? .hgt, .tiff, .asc, .dem and maybe others? 

Maybe I'm using _pyhgtmap_ wrong? 
--smooth How much should we put it on?
Is there any point in trying to use RGEalti files?

If you have any documents or just want to explain to me why these different formats and if it's feasible what I'm trying to do, thank you in advance.

### In French (native language)

Bonjour,

Je ne suis pas dans le domaine et j'ai du mal a savoir si ce que je cherche a faire est réalisable ou pas ou tout simplement inutile.

Je m'explique.

Je réalisé un rendu pour les appareils Garmin https://ravenfeld.gitlab.io/open-garmin-map/ grace a votre programme, encore merci.

Sauf que voila je trouve que les courbes de niveaux ne sont pas très lissé et que c'est peut etre lié au fichier que j'utiise. (Sonny 1° ou Nasa 1° pour les pays hors Europe).

Je me suis dit que pour la carte de la France je pourrais utiliser de meilleur fichier en utilisant les fichier RGEalti https://www.geoportail.gouv.fr/donnees/rge-alti-sources, mais les fichiers sont en .asc et non hgt.

J'ai essayé d'utiliser gdal pour les convertir mais sans réussite pour le moment.

En creusant un peu j'ai pu comprendre que le hgt avait une précision de 30m et que du coup passer d'un .asc a .hgt cela ne servirait a rien.
Deja c'est quoi la différence entre tout les formats ? .hgt,.tiff,.asc, .dem et peut etre d'autres ? 

C'est peut être _pyhgtmap_ que j'utilise mal ? 
--smooth on doit le mettre sur combien a 3 j'ai eu des soucis. 2 me semble bien non ?
Est ce que pour vous cela a un interet d'essayer d'utiliser les fichiers RGEalti ?

Si vous avez documents ou tout simplement serait m'expliquer pourquoi ses différents format et si c'est réalisable ce que je cherche a faire merci d'avance et merci de m'avoir lu jusqu'ici ;)

**Comment by ravenfeld** [comment]
I've just read that Sonny takes RGEAlti files, so I'll have to test it with his latest update to see if it's better.

**Comment by agrenott** [comment]
Hi, and thanks for your interested in pyhgtmap :). I'm French as well but will stick to English to ease sharing with other people.

Here is what I've found on ASC format: 
- https://surferhelp.goldensoftware.com/subsys/subsys_ASC_Arc_Info_ASCII_Grid.htm
- https://en.wikipedia.org/wiki/Esri_grid

And here is the header of a RGE Alti 1m .ASC file:
```
ncols        1000
nrows        1000
xllcorner    1021999.500000000000
yllcorner    6293000.500000000000
cellsize     1.000000000000
NODATA_value  -99999.00
 327.69 327.64 327.56 327.54 327.40 ...
```
So this file covers a 1000mx1000m square.

On the other hand, HGT format always covers a full 1°x1° (lon/lat) square, whatever its resolution. The bigger the file, the better the resolution. For eg. 1" HGT files contains 3 times as many point per dimension as 3" HGT files (3601 square side vs. 1201).

- https://cs108.epfl.ch/archive/17/p/04_elevation-profile.html

So if you can convert a set of RGE ASC alti files into huge HGT files, pyhgtmap should handle them (to be tested; I think resolution is computed automatically from file size, but I didn't check everywhere). 
But beware, computation will be much longer, and output probably much bigger as well!

Supporting natively ASC files would probably require a deeper refactoring of pyhgtmap, as it would need to break the "each tile is a 1°x1° one" assumption.

**Comment by agrenott** [comment]
> I've just read that Sonny takes RGEAlti files, so I'll have to test it with his latest update to see if it's better.

Indeed, but from the datasources file, he seems to rely on the 5m one (which is anyway down scaled to 30m for 1" HGT format): 
```
FRANCE (incl. Monaco, Guernsey, Jersey)
########################################

- Institut national de l’information géographique et forestière (IGN): RGE ALTI, DTM 5 m
https://geoservices.ign.fr/rgealti

- Métropole Bordeaux: DTM 0.5m
https://data.bordeaux-metropole.fr/data.php

- NASA: SRTM Version 3.0 Global 1" DTMs
https://dwtkns.com/srtm30m/
```

**Comment by ravenfeld** [comment]
Ok, so the hgt is not very precise. Do you know of another format that converts to an .osm that would be a little more accurate for smoother curves?

**Comment by agrenott** [comment]
It's not the HGT itself. It's only the default ones (3" and 1"). You could use HGT format with a 1m precision (so 1mx1m square for each point), but you would end up with a file 900 times bigger than an HGT 1" file (so about 22.5GB for a single tile).

**Comment by ravenfeld** [comment]
Thank you very much for all your answers. It may not be what I'm looking for as it's for a map Garmin. 
I'll try with the new Sonny files + the smooth of your program maybe it will be already very good.

**Comment by ravenfeld** [comment]
I tried with the new files but nothing exceptional, it's more the smooth=2 that brings something better but here's how to succeed and it's maybe not feasible to manage to smooth like on IGN's Scan25?


<img width="573" alt="Capture d’écran 2023-11-27 à 11 33 55" src="https://github.com/agrenott/pyhgtmap/assets/3765114/4b58009b-71d1-43cd-a17b-4d344c057838">

**Comment by agrenott** [comment]
I think you're rather looking for "--simplifyContoursEpsilon" option if you want to have simpler contour lines.

**Comment by ravenfeld** [comment]
I don't think so, because on hills, for example, they become polygons, almost squares, whereas they should be egg-shaped.

**Comment by ravenfeld** [comment]
I think it's the smoothing algo that's done afterwards because in red is my contour line and in violet is the one with 5M RGEAlti data and the background is the IGN map.
![482debcfd1568b7b620e783fe366930a66c58081](https://github.com/agrenott/pyhgtmap/assets/3765114/ddb88c50-41ca-484a-89a2-dcd967e1ba7a)

**Comment by ravenfeld** [comment]
I've found the data I need and they're already processed.

https://geoservices.ign.fr/courbes-de-niveau

The question is, do you know how to convert .shp files to .osm?

This image shows in red the .shp curve data and in blue the curve data from the hgt files.

It can be seen that the curves in red are those used by the ign for their Plan or scan 25 rendering.


<img width="775" alt="Capture d’écran 2023-11-27 à 16 59 39" src="https://github.com/agrenott/pyhgtmap/assets/3765114/61ebd6dc-15f8-4079-a4d4-c437d15230c5">

**Comment by ravenfeld** [comment]
For your information : https://github.com/roelderickx/ogr2osm

converts the file, but for the moment the tags are no good and are not processed by mkgmap.

**Comment by ravenfeld** [comment]
I found my answers to get there you have to look at this GitHub.

https://github.com/roelderickx/ogr2osm/issues/46

Thank you so much for helping me

**Comment by agrenott** [comment]
Thanks for sharing your findings.

**Comment by ravenfeld** [comment]
My conclusions for the moment for one department the weight of the card is almost the same but the rendering is much better in any case I find.
With the IGN contour data, you can see that they are the same as the Plan rendering.
<img width="470" alt="Capture d’écran 2023-11-28 à 20 22 47" src="https://github.com/agrenott/pyhgtmap/assets/3765114/c5b96192-b1e6-4047-adf5-7ec5f7dfe532">

With Sonny's hgt file
<img width="486" alt="Capture d’écran 2023-11-28 à 20 23 48" src="https://github.com/agrenott/pyhgtmap/assets/3765114/d340dc49-5fc6-44ae-8865-62cb07a64770">

I'm launching the whole creation for France this weekend I think, I'll come back to say if it's acceptable.

WARNING for the moment I don't know how to manage France + a border country.
