### ISSUE TITLE
Thanks for improvements!

### ISSUE THREAD

**Issue by mschlenstedt** [agrenott/pyhgtmap#4]
Hey,

I had no issue ;-) Just want to say thank you for your bugfixes and your version! It works like a charme on Linux Mint 21.1 while the original one fails due to the changes of the matplotlib.

I would prefer to make your Git Repo the standard source for phyghtmap... https://wiki.openstreetmap.org/wiki/User_talk:Panarchos#ValueError:_too_many_values_to_unpack_-_Solution

Thanks again!

**Comment by agrenott** [comment]
Thanks a lot for the feedback!
I tried contacting the author, but got no reply yet. I guess I'll end up "officially" forking this package...

**Comment by mschlenstedt** [comment]
I think this would be a great idea! Furthermore, Github is a much better place to develope software and feedback/bugfixes than a Wiki discussion page....
