### ISSUE TITLE
pyhgtmap failing with one specific poly file with multipolygon and datasource sonn1

### ISSUE THREAD

**Issue by keenonkites** [agrenott/pyhgtmap#42]
Happy New Year !

I've run into a problem while trying to build contour file from source sonn1 with a polygon file that contains a multipolygon.
The errormessage points me into the direction that ithas to do with the multipolygon, but we have other multipolygon cases that didn't fail (at least I didn't notice it) and the final map was built correctly.
Possibly there is something very specific with this poly file or pyhgtmap runs through other code branches than with other poly files..... or we have a problem with all multipolygon files and didn't notice it yet.

I will try to build other contour files with other multipolygon to find out more from my end too.

The actual error I get ist:
```
  File "/home/xxx/venv_pyhgtmap/bin/pyhgtmap", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/venv_pyhgtmap/lib/python3.8/site-packages/pyhgtmap/main.py", line 593, in main
    main_internal(sys.argv[1:])
  File "/home/xxx/venv_pyhgtmap/lib/python3.8/site-packages/pyhgtmap/main.py", line 585, in main_internal
    HgtFilesProcessor(opts.nJobs, opts.startId, opts.startWayId, opts).process_files(
  File "/home/xxx/venv_pyhgtmap/lib/python3.8/site-packages/pyhgtmap/hgt/processor.py", line 268, in process_files
    self.process_file(file_name, check_poly)
  File "/home/xxx/venv_pyhgtmap/lib/python3.8/site-packages/pyhgtmap/hgt/processor.py", line 222, in process_file
    hgt_tiles = hgt_file.makeTiles(self.options)
  File "/home/xxx/venv_pyhgtmap/lib/python3.8/site-packages/pyhgtmap/hgt/file.py", line 668, in makeTiles
    chopData(bbox, truncatedData)
  File "/home/xxx/venv_pyhgtmap/lib/python3.8/site-packages/pyhgtmap/hgt/file.py", line 640, in chopData
    tileMask = polygon_mask(
  File "/home/xxx/venv_pyhgtmap/lib/python3.8/site-packages/pyhgtmap/hgt/file.py", line 275, in polygon_mask
    clipped_polygons.append([(x, y) for x, y in clipped_p.exterior.coords])
AttributeError: 'GeometryCollection' object has no attribute 'exterior'
```

I found interesting information at the following link:
https://stackoverflow.com/questions/64099107/convert-multipolygon-geometry-into-list

As I can not attach the poly file here directly, please find it at:
https://github.com/freizeitkarte/fzk-mde-garmin/blob/c99ffbb32d7439e5d9c7d4288b76054d11405f8b/Freizeitkarte-Entwicklung/poly/Freizeitkarte_GBR%2B.poly

Hope this helps to fix it.

Cheers Patrik

**Comment by agrenott** [comment]
Hi, and happy new year!
I've been able to reproduce. It's actually a specific tile of sonn1 (no issue with sonn3):
`python ../../pyhgtmap/main.py --pbf --source=sonn1 --polygon=Freizeitkarte_GBR+.poly --log=DEBUG hgt/SONN1/N49E000.hgt`

I guess it's linked to computed intersections of the polygon(s) and the tile bounding box.

**Comment by agrenott** [comment]
This is actually not because the input is a multi-polygon, but because the intersection of the first polygon with the tile bounding box is a heterogeneous collection of polygon and line (in orange below) :

![image](https://github.com/agrenott/pyhgtmap/assets/12431371/407ec406-d44c-4eb7-83dd-ed939345a0c1)

Green is the result after fixing the function.
