### ISSUE TITLE
Coordinate Transformation in ContourGenerator::trace is not applied

### ISSUE THREAD

**Issue by kolrami** [agrenott/pyhgtmap#47]
While trying to setup data for rendering OpenTopoMaps I tried to replace the no longer maintained phyghtmap by this project. First of all thank you very much for further maintaining this fork :)

While following the guide in OpenTopoMaps, I encountered a problem with a tif in EPSG:3857. It produced an invalid OSM XML with coordinates in EPSG:3857 instead of the expected EPSG:4326. See an example below.

```
<?xml version="1.0" encoding="utf-8"?>
<osm version="0.6" generator="pyhgtmap 3.6">
<bounds minlat="48.0001861" minlon="5.9999876" maxlat="52.0001678" maxlon="17.9995035"/>
<node id="10000000" lat="6608469.6395790" lon="723805.5616385" version="1"/>
<node id="10000001" lat="6608455.7934252" lon="723769.5616385" version="1"/>
```

I had a look at the implementation and I think the issue came up with the simplification in https://github.com/agrenott/pyhgtmap/commit/8fc9edd504f543bf7d55cddd2b3001e8d36aefea. Here we removed the `clipPath` method and with that, we also removed the transformation. The old comment actually stated _This method also does a potentially needed transformation of the projection_ and as a first step the projection was applied.

```
298>        # do the transform if necessary
299>        if self.transform != None:
300>            path = numpy.array(self.transform(path))
```

After removing the `clipPath` method also the transformation is no longer applied, in fact the `self.transformation` is no longer used at all as far as I can see. I think we should add again the snippet from above to the `trace` method? I already quickly tried to do something like this (although I am not 100% sure how to correctly handle the `numpy.ndarray`) and it produced better looking coordinates.

**Comment by kolrami** [comment]
In case you want to reproduce, I used the 3" data from viewfinder and pre-processed it like followed.

```
for hgt in *.hgt; do gdal_fillnodata.py $hgt $hgt.tif; done
gdal_merge.py -n 32767 -co COMPRESS=LZW -co PREDICTOR=2 -o raw.tif *.hgt.tif
gdalwarp -co COMPRESS=LZW -co PREDICTOR=2 -t_srs "+proj=merc +ellps=sphere +R=6378137 +a=6378137 +units=m" -r bilinear -tr 90 90 raw.tif warp-90.tif

```

**Comment by agrenott** [comment]
Thanks for the detailed bug report and first investigation. I'll have a look.
