### ISSUE TITLE
Problem with source ALOS1 if file is not found on server - crash

### ISSUE THREAD

**Issue by keenonkites** [agrenott/pyhgtmap#52]
Hi,

after successful downloading and building elevation for Luxembourg (small and handy) I tried today with really needed areas, where we do not find any SRTM1 data: enlarged Finland and northern part of enlarged Norway.

Unfortunately pyhgtmap bails out already while trying to download data from the server. Without looking deeper into it I think it has to do that some files are not found on the server and that pyhgtmap stops execution with an exception.

I'm not sure if the file would really be needed or is somwhere, where anyway no data exists due to no landmass or similar. But in my opinion the script should warn as with other sources something like 'file not found on server' instead of stopping execution.

Could you please have a look at it ? Below you find part (in my opinion the important part) of pyhgtmap output. And attached you find two poly files (in the zip) that didn't build proper maps but just have thrown exceptions.

If you need more details or further tests, just let me know.

Thanks and regards
Patrik

------------------------------------
Output of pyhgtmap:

```
...
checking if area N70E032 intersects with polygon ... no
N59E018: trying alos1 ...
N60E018: trying alos1 ...
N61E018: trying alos1 ...
  File "/home/pab/miniconda3/lib/python3.12/site-packages/pyhgtmap/sources/__init__.py", line 111, in get_file
    self.check_cached_file(file_name, resolution)
  File "/home/pab/miniconda3/lib/python3.12/site-packages/pyhgtmap/sources/__init__.py", line 94, in check_cached_file
    raise FileNotFoundError(f"File {file_name} not found")
FileNotFoundError: File ./hgt/ALOS1/N61E018.tif not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pab/miniconda3/bin/pyhgtmap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pab/miniconda3/lib/python3.12/site-packages/pyhgtmap/main.py", line 67, in main
    main_internal(sys.argv[1:])
  File "/home/pab/miniconda3/lib/python3.12/site-packages/pyhgtmap/main.py", line 45, in main_internal
    hgtDataFiles = NASASRTMUtil.getFiles(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pab/miniconda3/lib/python3.12/site-packages/pyhgtmap/NASASRTMUtil.py", line 762, in getFiles
    saveFilename = sources_pool.get_file(opener, area, source)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pab/miniconda3/lib/python3.12/site-packages/pyhgtmap/NASASRTMUtil.py", line 731, in get_file
    file_name = self._real_pool.get_source(source[0:4]).get_file(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pab/miniconda3/lib/python3.12/site-packages/pyhgtmap/sources/__init__.py", line 122, in get_file
    self.download_missing_file(area, resolution, file_name)
  File "/home/pab/miniconda3/lib/python3.12/site-packages/pyhgtmap/sources/alos.py", line 103, in download_missing_file
    with ZipFile(
         ^^^^^^^^
  File "/home/pab/miniconda3/lib/python3.12/zipfile/__init__.py", line 1341, in __init__
    self._RealGetContents()
  File "/home/pab/miniconda3/lib/python3.12/zipfile/__init__.py", line 1408, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
[problematic-poly.zip](https://github.com/agrenott/pyhgtmap/files/15081825/problematic-poly.zip)

**Comment by keenonkites** [comment]
I've checked a bit deeper and with the polygon files I've tested so far, it bails out on the following tiles:

FileNotFoundError: File ./hgt/ALOS1/N55E003.tif not found
FileNotFoundError: File ./hgt/ALOS1/N55E019.tif not found
FileNotFoundError: File ./hgt/ALOS1/N61E018.tif not found
FileNotFoundError: File ./hgt/ALOS1/N65E008.tif not found

According to [Alos1 coverage](https://www.eorc.jaxa.jp/ALOS/en/dataset/aw3d30/aw3d30_e.htm) this are water tiles. No wonder they are not found on the alos1 server.

Cheers Patrik

**Comment by agrenott** [comment]
Hi, thanks for the detailed report. Should be fixed on master branch.

**Comment by keenonkites** [comment]
I'll do a test run as soon as the server isn't busy anymore. But that'll be probably only next week.
Thanks for fixing.

Cheers Patrik

**Comment by keenonkites** [comment]
I can confirm that ALOS1 problem with 'missing' file is solved. Thanks for fixing it. We've build several contour data files from very North in Europe and Russia and they all are built properly and we didn't find any obvious problems.

Cheers Patrik
